### ISSUE TITLE
Edit Profile Page

### ISSUE THREAD

**Issue by renodubois** [siggame/ophelia#115]

**Comment by cmparsons** [comment]
I'm thinking about using [Formik](https://github.com/jaredpalmer/formik) to write the form. It's pretty popular and helps standardize using forms, and we could  use it for other forms.

**Comment by renodubois** [comment]
If this form goes well, we can definitely convert our existing forms to use Formik as well. Let's get this merged in and see how it looks from there.

**Comment by cmparsons** [comment]
For some reason, I am getting a 401 on a PUT request to users/:teamName

**Comment by cmparsons** [comment]
Never mind about the 401. I found my problem. I was passing the data wrong in my put request. I was passing it as ```axios.put(endpoint, { /* auth headers */ }, { params: /* data */ })``` instead of ```axios.put(endpoint, { /* data */ }, { /* auth headers */})```.

When the request was received by the server, it couldn't find the authorization headers because they were actually in the body of the request.

The endpoint works like it should.

**Comment by renodubois** [comment]
Fixed by #161.
